development:
    email: 
    website: http://dev:3000/weekly-report
test:

production:
    email: 
        address: " "
        port: 000
        domain: " "
        user_name: " "
        password: " "
        authentication: " "
    website: