development:
    email: 
    website: 
test:

production:
    email: 
        address: ""
        port: 000
        # domain: "jemaf.rhcloud.com"
        user_name: ""
        password: ""
        authentication: ""
        sender: ""
        receiver: ""
    website: 